elasticsearch.hosts:
- http://elasticsearch:9200
elasticsearch.password: owxkjG0uKX6Jj2Yq
elasticsearch.username: kibana_system
monitoring.ui.container.elasticsearch.enabled: true
server.host: 0.0.0.0
server.name: kibana
