elasticsearch.hosts:
- http://elasticsearch:9200
elasticsearch.password: changeme
elasticsearch.username: elastic
monitoring.ui.container.elasticsearch.enabled: true
server.host: 0.0.0.0
server.name: kibana
